In [2]:
#!pip install pandas

In [97]:
import pandas as pd
import warnings


warnings.filterwarnings("ignore")

In [98]:
df = pd.read_csv(r"C:\Users\MC\Documents\Projects\Kaggle\Datasets\messy_students.csv")

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         9 non-null      object
 3   City        10 non-null     object
 4   Marks       9 non-null      float64
 5   Enrolled    9 non-null      object
 6   SignupDate  10 non-null     object
dtypes: float64(1), int64(1), object(5)
memory usage: 692.0+ bytes

In [100]:
df["Age"].replace("twenty-two","22",inplace=True)

In [101]:
my_dict = {
    "Y" : "Yes",
    "yes" : "Yes",
    "N" :"No",
    "no" : "No",
    "YES" : "Yes"
}

df["Enrolled"].replace(my_dict,inplace=True)

In [102]:
my_date_dict = {
    "05/02/2025"  :  "2025-05-02",
    "2025/03/10"   : "2025-03-10",
    "2025/06/20"   : "2025-06-20",
    "20-07-2025"  :  "2025-07-20",
    "2025/08/15"  :  "2025-08-15",
    "2025/09/01"  :  "2025-09-01"
}

df["SignupDate"].replace(my_date_dict,inplace=True)

In [103]:
df["Age"] = pd.to_numeric(df["Age"],errors="coerce")

In [104]:
df["Age"].fillna(df["Age"].mean(),inplace=True)

In [105]:
df.head(10)

    ID     Name   Age          City  Marks Enrolled  SignupDate
0  101   Alice   23.0  johannesburg   88.0      Yes  2025-01-05
1  102      bob  25.0     Cape Town   75.0      Yes  2025-05-02
2  103  Charlie  22.0        Durban   93.0      Yes  2025-03-10
3  104    David  24.0     Pretoria    68.0       No  2025-04-12
4  105     Ella  21.0  Bloemfontein    NaN       No  2025-05-01
5  105     Ella  21.0  Bloemfontein   90.0       No  2025-05-01
6  106   Fatima  24.0  Johannesburg   85.0      Yes  2025-06-20
7  107     Gugu  27.0       gauteng  101.0      Yes  2025-07-20
8  108     Hugo  29.0        Durban   47.0       No  2025-08-15
9  109      Ian  24.0     Cape town   68.0      NaN  2025-09-01

In [106]:
df.sort_values(by="Marks",na_position="last",inplace=True)

In [107]:
df=df.drop_duplicates(subset=["Name","ID"],keep="first")

In [108]:
df.head(10)

    ID     Name   Age          City  Marks Enrolled  SignupDate
8  108     Hugo  29.0        Durban   47.0       No  2025-08-15
3  104    David  24.0     Pretoria    68.0       No  2025-04-12
9  109      Ian  24.0     Cape town   68.0      NaN  2025-09-01
1  102      bob  25.0     Cape Town   75.0      Yes  2025-05-02
6  106   Fatima  24.0  Johannesburg   85.0      Yes  2025-06-20
0  101   Alice   23.0  johannesburg   88.0      Yes  2025-01-05
5  105     Ella  21.0  Bloemfontein   90.0       No  2025-05-01
2  103  Charlie  22.0        Durban   93.0      Yes  2025-03-10
7  107     Gugu  27.0       gauteng  101.0      Yes  2025-07-20

In [110]:
df["Marks"]= df["Marks"].clip(upper=100)

In [111]:
df.head(10)

    ID     Name   Age          City  Marks Enrolled  SignupDate
8  108     Hugo  29.0        Durban   47.0       No  2025-08-15
3  104    David  24.0     Pretoria    68.0       No  2025-04-12
9  109      Ian  24.0     Cape town   68.0      NaN  2025-09-01
1  102      bob  25.0     Cape Town   75.0      Yes  2025-05-02
6  106   Fatima  24.0  Johannesburg   85.0      Yes  2025-06-20
0  101   Alice   23.0  johannesburg   88.0      Yes  2025-01-05
5  105     Ella  21.0  Bloemfontein   90.0       No  2025-05-01
2  103  Charlie  22.0        Durban   93.0      Yes  2025-03-10
7  107     Gugu  27.0       gauteng  100.0      Yes  2025-07-20

In [112]:
df["City"] = df["City"].str.capitalize()

In [113]:
df.head(10)

    ID     Name   Age          City  Marks Enrolled  SignupDate
8  108     Hugo  29.0        Durban   47.0       No  2025-08-15
3  104    David  24.0     Pretoria    68.0       No  2025-04-12
9  109      Ian  24.0     Cape town   68.0      NaN  2025-09-01
1  102      bob  25.0     Cape town   75.0      Yes  2025-05-02
6  106   Fatima  24.0  Johannesburg   85.0      Yes  2025-06-20
0  101   Alice   23.0  Johannesburg   88.0      Yes  2025-01-05
5  105     Ella  21.0  Bloemfontein   90.0       No  2025-05-01
2  103  Charlie  22.0        Durban   93.0      Yes  2025-03-10
7  107     Gugu  27.0       Gauteng  100.0      Yes  2025-07-20

In [114]:
df["Enrolled"].fillna("Unknown",inplace=True)

In [116]:
grade_dict = {
    "A": (80, 100),
    "B": (70, 79), 
    "C": (60, 69), 
    "D": (50, 59),
    "E": (40, 49),
    "F": (0, 39) 
}

def assign_grade(marks):
    for grade, (low, high) in grade_dict.items():
        if low <= marks <= high:
            return grade
    return "Invalid"

In [117]:

df["Grade"] = df["Marks"].apply(assign_grade)

In [119]:
df.head(10)

    ID     Name   Age          City  Marks Enrolled  SignupDate Grade
8  108     Hugo  29.0        Durban   47.0       No  2025-08-15     E
3  104    David  24.0     Pretoria    68.0       No  2025-04-12     C
9  109      Ian  24.0     Cape town   68.0  Unknown  2025-09-01     C
1  102      bob  25.0     Cape town   75.0      Yes  2025-05-02     B
6  106   Fatima  24.0  Johannesburg   85.0      Yes  2025-06-20     A
0  101   Alice   23.0  Johannesburg   88.0      Yes  2025-01-05     A
5  105     Ella  21.0  Bloemfontein   90.0       No  2025-05-01     A
2  103  Charlie  22.0        Durban   93.0      Yes  2025-03-10     A
7  107     Gugu  27.0       Gauteng  100.0      Yes  2025-07-20     A

In [ ]:
#Plots